### ISSUE TITLE
Do the boost-nar artifacts get deployed to Maven Central / Sonatype OSSRH ?

### ISSUE THREAD

**Issue by bcopy** [markjohndoyle/boost-nar#17]
Hi,

I was wondering if there was any interest in deploying the Boost NAR artifacts to maven central : 

http://central.sonatype.org/pages/ossrh-guide.html

**Comment by dproteus13** [comment]
I'd love to see this happen and be a success.  However, I strongly suspect
it would fail miserably because of your other comment: Boost is so
configurable, and NAR doesn't really have a way to handle all of those
permutations cleanly. For the strictly header portions of Boost it might be
more feasible?

**Comment by bcopy** [comment]
I agree, not being a Boost expert, I realise there are hundreds of possible tweaks via DEFINE that may greatly influence the code that's written against the libs. I think it would only make sense inside a given organisation.
